### PR TITLE
FIX: net-lisias-ksp/TweakScaleCompanion_MultiPass #3

### PR DESCRIPTION
**Pull request by 7ranceaddic7**

### CODE REVIEW

**Comment by Lisias** [comment]
Something wrong with the commit?

I just noticed this PR now that you had closed it.

**Comment by 7ranceaddic7** [comment]
No,  that would be me closing the wrong thing.

**Comment by Lisias** [comment]
It will take a few more days until I have a window of opportunity to handle patches again. But I will.

**Comment by Lisias** [comment]
DAMN.

I completely forgot about this one. Unfortunately, I ended up working it on https://github.com/TweakScale/Companion/issues/15 .

My apologies!!!

**Pull request closed without merging**
